GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5e2f93aa180fcd4ddcb2d859

###


POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/5e2f93aa180fcd4ddcb2d859